### ISSUE TITLE
Losing Mobs to plugin

### ISSUE THREAD

**Issue by SirCreep** [Joannou1/GLServers#59]
Ive spawned 4 cows to start a farm using eggs and they all disappeared right after I spawned them. I later found out that its because of a plugin that removes these mobs to make it less laggy. Is it all possible to remove this plugin? Also we need to bring back the melon shop best store that was ever on this server. We should also be able to sell our ores and stuff to the market like we could when the server started up. Thank you for your consideration :D

**Comment by TyJcksn** [comment]
I'll be glad to give you some cow eggs to fix this.

**Comment by Cbjax** [comment]
On old GLD we had a great way of getting people to know a little bit about GLD before they whent off they had to go throw a sorta quation maze thing. This helped in 2 ways, one in like 2m they knew how to make money what were some of the big rules and the basics of GLD. The other way it helped it cut back of the silly questions asked in /h that everyone face palms to. like http://prntscr.com/4vnrov or http://prntscr.com/4vns3h. We kinda been needing something to tell people basic info on GLD for along time. So eather quotation maze thing or signs at spawn or even a book. Books would be nice because sometimes signs at spawn look ugly. Thank you for reading this! Have a problem with my grammar or spelling? i am past the point of help.

**Comment by TyJcksn** [comment]
I think adding a starter book into the first logon kit would be a great idea, one that was a page or two explaining about the server in very simplistic terms.

**Comment by Cbjax** [comment]
Maybe add 2 books to the logon kit. One for basic info for lazy people and one for people that want to know about all the server in great detail. Just "Spit balling" here!
