### ISSUE TITLE
The economy debate

### ISSUE THREAD

**Issue by Kindofjakii** [Joannou1/GLServers#63]
Right, obviously a pressing issue, anyone wanting to present any suggestions, post in here. Obviously mention why certain elements are such an issue and the things needed to be implemented to change that.

**Comment by Cbjax** [comment]
The economy is for sure a pressing issue that needs to be solved ASP. The main problem of the economy right now is that Mrlight keeps getting drained. Why is he getting drained? The reason why he is getting drained is that everything in the market a player can undersell and make money. For an example obsidian at the market is 5k a stack. Yet the standered price that players sell obsidian for right now is 2.5-3k a stack. Mrlight is getting 0ls from this sell sign a day. Now if you priced it low like say 1-2k a stack then it would not be worth the time for people to mine it and sell it or mine it for themselves there for it would give Mrlight money. There are tons of ways that players can make money trow trade and sell signs so distorting the market for obsidian will not do much. Changing the sell sign for obsidian will not be the panacea to the economy. There must be 5-6 Items that are bought all the time and are priced so cheap that players will think its not worth there time and effort to mine/enchant/make the item and sell it. Why not just keep giving Mrlight money? Well giving Mrlight money all the time at first will have no effect on the economy, but slowly the economy will start to have inflation at a rate that GLD can't keep up with. There will always be inflation because when a new player joins GLD they get 3k and when you buy a rank you get LS and when people vote but its at a rate that GLD can handle. Now some people are suggesting that we should bring back sell signs like Gold and Iron. There are 2 big problems with this. One It worked on GLD because spawners where around what 45k and almost anyone could afford them. If we added spawners back to the market then it would not be fair to the people who bought MS. A few Months before OLD GLD was replaced with NEW GLD staff made spawners stop spawning things because people started to make sorters and it damaged the economy. Also they stopped selling spawners at market 3 or 4 weeks before that because of the all the lag it was causing. Many people think that the price of the diamond should be raised (me include). Now i'm not saying we should change the price now but i think after changing the buy signs that may or may not fix mrlight so he is not drained so easily, then we should raise the price a tinny bit to like 3k if he is fixed. So that new players have a little easier time getting money. Also there should be a sell sign for gold ore. So that we can sell all ores when we go mining. (Note: When ever you change the sell sign of diamonds people will sell tons of it in the first 2 weeks because they want to get ride of there stored amount because there afraid the price might change. After this it should go back to the normal amount of people selling it per a day) Ok now lets talk about the donor market. Now the donor market right now i am 90% sure that non-donors can go in to, but if we where to fix this then we need to update it. There should only be stuff that is not used in a daily basis. Donor's can make money so much easier then non-donors its not even funny so lets not give donors another big advantage bye having tons of stuff in it dirt cheap. That said we should still give people a reason to buy S-T. On old GLD the only way to get mob eggs was from donors. MOB eggs where only sold in the donor market. There for the only way a new player could get a nice creeper egg (Old gld's kit starter did not have a creeper egg in it) was buying it from a donor. This did not effect the economy that much. Donor's did not make tons of money off this but it was enough to give incentive to buy S-T. Right now i don't see a reason why to buy S-T because you can get mob eggs any time at the normal market. The Economy is a very controversial topic and I invite people to Post other idea's and challenge my idea's but please do this in a mannerly faction because this is a topic that need to be discussed and I do not want this closed (On forums there was a thread about that was closed because it got out of hand really fast)   If you have gotten this far you are not lazy!

**Comment by TyJcksn** [comment]
Mrlight has been given 30million, problem solved.
