### ISSUE TITLE
Missing Perks / Bugs

### ISSUE THREAD

**Issue by TyJcksn** [Joannou1/GLServers#68]
- 1.8 is officially out, so maybe /disguise can come back non laggy?
- [12/5/14, 11:44:16 PM] Fluffeh GLD/ Zak: Riding people buggy
  [12/5/14, 11:44:23 PM] Fluffeh GLD/ Zak: People see your asscheeks when they should see nothing.
- /mc (magic carpet) gives an internal error
- TP bow should come back for gifted (if it works only for a specific bow)
- Risen Titan pets used to crash players, if an update comes out it may not 
- Hoppers seem to be broken
- Players can hit and break armor stands just like they could with item frames before, we probably will need to wait for a plugin to come out
- Light rolls need to be fixed

**Comment by TyJcksn** [comment]
Disguise plugin for players, less of a lag issue? It has 64 disguises so maybe give players around 5 mobs per rank?
http://www.spigotmc.org/resources/libs-disguises.81/

**Comment by Kladdkaka** [comment]
Yes, please use libs disguise instead of the other plugin.

**Comment by Cbjax** [comment]
./pce is broken sadly
Also due to the clear lag armour stands clear every 15.
Axes are unable to break leaves.
When using your hand and you use the hand version of super breaker you are unable to break blocks. 
Also I really think we should have server restarts more often and get ride of the burger. Btw i typing from my iPod please excuse any errors.

**Comment by TyJcksn** [comment]
All fixed
